'use strict';

require('mocha');
const fs = require('fs');
const path = require('path');
const glob = require('glob');
const assert = require('assert');
const converter = require('..');
const cwd = path.resolve.bind(path, __dirname);

function read(fp) {
  return fs.readFileSync(fp, 'utf8');
}
function fixture(name) {
  return read(cwd('fixtures', name));
}
function expected(name) {
  return read(cwd('expected', name));
}

describe('shopify themes', function() {
  this.timeout(20000);

  const files = glob.sync('shopify-*/**/*.{*liquid*,json}', { cwd: cwd('fixtures') });

  files.forEach(file => {
    const to = file.replace(/\.liquid$/, '.hbs');
    const actual = converter.convert(fixture(file));
    it('should convert ' + file, () => assert.equal(actual, expected(to)));
  });

  const fixtures = [
    'shopify-debut/assets/gift-card.scss.liquid',
    'shopify-debut/assets/ico-select.svg.liquid',
    'shopify-debut/assets/theme.scss.liquid',
    'shopify-debut/config/settings_data.json',
    'shopify-debut/config/settings_schema.json',
    'shopify-debut/layout/gift_card.liquid',
    'shopify-debut/layout/password.liquid',
    'shopify-debut/layout/theme.liquid',
    'shopify-debut/locales/de.json',
    'shopify-debut/locales/en.default.json',
    'shopify-debut/locales/es.json',
    'shopify-debut/locales/fr.json',
    'shopify-debut/locales/ja.json',
    'shopify-debut/locales/pt-BR.json',
    'shopify-debut/locales/pt-PT.json',
    'shopify-debut/sections/article-template.liquid',
    'shopify-debut/sections/blog-template.liquid',
    'shopify-debut/sections/cart-template.liquid',
    'shopify-debut/sections/collection-list.liquid',
    'shopify-debut/sections/collection-template.liquid',
    'shopify-debut/sections/collection.liquid',
    'shopify-debut/sections/custom-content.liquid',
    'shopify-debut/sections/feature-columns.liquid',
    'shopify-debut/sections/feature-row.liquid',
    'shopify-debut/sections/featured-blog.liquid',
    'shopify-debut/sections/featured-product.liquid',
    'shopify-debut/sections/footer.liquid',
    'shopify-debut/sections/header.liquid',
    'shopify-debut/sections/hero.liquid',
    'shopify-debut/sections/image-bar.liquid',
    'shopify-debut/sections/list-collections-template.liquid',
    'shopify-debut/sections/logo-bar.liquid',
    'shopify-debut/sections/map.liquid',
    'shopify-debut/sections/newsletter.liquid',
    'shopify-debut/sections/password-content.liquid',
    'shopify-debut/sections/password-footer.liquid',
    'shopify-debut/sections/password-header.liquid',
    'shopify-debut/sections/product-template.liquid',
    'shopify-debut/sections/quotes.liquid',
    'shopify-debut/sections/slideshow.liquid',
    'shopify-debut/snippets/bgset.liquid',
    'shopify-debut/snippets/collection-grid-item.liquid',
    'shopify-debut/snippets/comment.liquid',
    'shopify-debut/snippets/google-fonts.liquid',
    'shopify-debut/snippets/icon-amazon_payments.liquid',
    'shopify-debut/snippets/icon-american_express.liquid',
    'shopify-debut/snippets/icon-apple_pay.liquid',
    'shopify-debut/snippets/icon-arrow-left.liquid',
    'shopify-debut/snippets/icon-arrow-right.liquid',
    'shopify-debut/snippets/icon-bitcoin.liquid',
    'shopify-debut/snippets/icon-cart.liquid',
    'shopify-debut/snippets/icon-chevron-down.liquid',
    'shopify-debut/snippets/icon-chevron-left.liquid',
    'shopify-debut/snippets/icon-chevron-right.liquid',
    'shopify-debut/snippets/icon-chevron-up.liquid',
    'shopify-debut/snippets/icon-cirrus.liquid',
    'shopify-debut/snippets/icon-close.liquid',
    'shopify-debut/snippets/icon-dankort.liquid',
    'shopify-debut/snippets/icon-diners_club.liquid',
    'shopify-debut/snippets/icon-discover.liquid',
    'shopify-debut/snippets/icon-dogecoin.liquid',
    'shopify-debut/snippets/icon-dwolla.liquid',
    'shopify-debut/snippets/icon-facebook.liquid',
    'shopify-debut/snippets/icon-forbrugsforeningen.liquid',
    'shopify-debut/snippets/icon-hamburger.liquid',
    'shopify-debut/snippets/icon-instagram.liquid',
    'shopify-debut/snippets/icon-interac.liquid',
    'shopify-debut/snippets/icon-jcb.liquid',
    'shopify-debut/snippets/icon-laser.liquid',
    'shopify-debut/snippets/icon-litecoin.liquid',
    'shopify-debut/snippets/icon-lock.liquid',
    'shopify-debut/snippets/icon-login.liquid',
    'shopify-debut/snippets/icon-maestro.liquid',
    'shopify-debut/snippets/icon-master.liquid',
    'shopify-debut/snippets/icon-minus.liquid',
    'shopify-debut/snippets/icon-pause.liquid',
    'shopify-debut/snippets/icon-paypal.liquid',
    'shopify-debut/snippets/icon-pin.liquid',
    'shopify-debut/snippets/icon-pinterest.liquid',
    'shopify-debut/snippets/icon-play-video.liquid',
    'shopify-debut/snippets/icon-play.liquid',
    'shopify-debut/snippets/icon-plus.liquid',
    'shopify-debut/snippets/icon-quote.liquid',
    'shopify-debut/snippets/icon-rss.liquid',
    'shopify-debut/snippets/icon-search.liquid',
    'shopify-debut/snippets/icon-shopify-logo.liquid',
    'shopify-debut/snippets/icon-snapchat.liquid',
    'shopify-debut/snippets/icon-stripe.liquid',
    'shopify-debut/snippets/icon-tumblr.liquid',
    'shopify-debut/snippets/icon-twitter.liquid',
    'shopify-debut/snippets/icon-vimeo.liquid',
    'shopify-debut/snippets/icon-visa.liquid',
    'shopify-debut/snippets/icon-youtube.liquid',
    'shopify-debut/snippets/image-style.liquid',
    'shopify-debut/snippets/no-blocks.liquid',
    'shopify-debut/snippets/pagination.liquid',
    'shopify-debut/snippets/product-card-grid.liquid',
    'shopify-debut/snippets/product-card-list.liquid',
    'shopify-debut/snippets/product-price.liquid',
    'shopify-debut/snippets/search-form.liquid',
    'shopify-debut/snippets/site-nav.liquid',
    'shopify-debut/snippets/social-meta-tags.liquid',
    'shopify-debut/snippets/social-sharing.liquid',
    'shopify-debut/templates/404.liquid',
    'shopify-debut/templates/article.liquid',
    'shopify-debut/templates/blog.liquid',
    'shopify-debut/templates/cart.liquid',
    'shopify-debut/templates/collection.liquid',
    'shopify-debut/templates/customers/account.liquid',
    'shopify-debut/templates/customers/activate_account.liquid',
    'shopify-debut/templates/customers/addresses.liquid',
    'shopify-debut/templates/customers/login.liquid',
    'shopify-debut/templates/customers/order.liquid',
    'shopify-debut/templates/customers/register.liquid',
    'shopify-debut/templates/customers/reset_password.liquid',
    'shopify-debut/templates/gift_card.liquid',
    'shopify-debut/templates/index.liquid',
    'shopify-debut/templates/list-collections.liquid',
    'shopify-debut/templates/page.contact.liquid',
    'shopify-debut/templates/page.liquid',
    'shopify-debut/templates/password.liquid',
    'shopify-debut/templates/product.liquid',
    'shopify-debut/templates/search.liquid',
    'shopify-naked/assets/shop.js.liquid',
    'shopify-naked/assets/style.scss.liquid',
    'shopify-naked/config/settings_data.json',
    'shopify-naked/config/settings_schema.json',
    'shopify-naked/layout/theme.liquid',
    'shopify-naked/snippets/open-graph-tags.liquid',
    'shopify-naked/snippets/product-item.liquid',
    'shopify-naked/snippets/site-nav.liquid',
    'shopify-naked/snippets/twitter-card.liquid',
    'shopify-naked/templates/404.liquid',
    'shopify-naked/templates/article.liquid',
    'shopify-naked/templates/blog.liquid',
    'shopify-naked/templates/cart.liquid',
    'shopify-naked/templates/collection.liquid',
    'shopify-naked/templates/index.liquid',
    'shopify-naked/templates/page.liquid',
    'shopify-naked/templates/product.liquid',
    'shopify-naked/templates/search.liquid',
    'shopify-skeleton/assets/arrow-down.svg.liquid',
    'shopify-skeleton/assets/cart.svg.liquid',
    'shopify-skeleton/assets/shop.js.liquid',
    'shopify-skeleton/assets/style.scss.liquid',
    'shopify-skeleton/config/settings_data.json',
    'shopify-skeleton/layout/theme.liquid',
    'shopify-skeleton/snippets/article-grid-item.liquid',
    'shopify-skeleton/snippets/collection-grid-item.liquid',
    'shopify-skeleton/snippets/collection-listing.liquid',
    'shopify-skeleton/snippets/open-graph-tags.liquid',
    'shopify-skeleton/snippets/product-grid-item.liquid',
    'shopify-skeleton/snippets/site-nav.liquid',
    'shopify-skeleton/snippets/social-links.liquid',
    'shopify-skeleton/snippets/twitter-card.liquid',
    'shopify-skeleton/templates/404.liquid',
    'shopify-skeleton/templates/article.liquid',
    'shopify-skeleton/templates/blog.grid.liquid',
    'shopify-skeleton/templates/blog.liquid',
    'shopify-skeleton/templates/cart.liquid',
    'shopify-skeleton/templates/collection.liquid',
    'shopify-skeleton/templates/index.liquid',
    'shopify-skeleton/templates/list-collections.liquid',
    'shopify-skeleton/templates/page.liquid',
    'shopify-skeleton/templates/product.liquid',
    'shopify-skeleton/templates/search.liquid',
    'shopify-timber/assets/ajax-cart.js.liquid',
    'shopify-timber/assets/gift-card.scss.liquid',
    'shopify-timber/assets/ico-select.svg.liquid',
    'shopify-timber/assets/icons.json',
    'shopify-timber/assets/timber.js.liquid',
    'shopify-timber/assets/timber.scss.liquid',
    'shopify-timber/layout/theme.liquid',
    'shopify-timber/snippets/ajax-cart-template.liquid',
    'shopify-timber/snippets/blog-sidebar.liquid',
    'shopify-timber/snippets/breadcrumb.liquid',
    'shopify-timber/snippets/collection-sidebar.liquid',
    'shopify-timber/snippets/collection-sorting.liquid',
    'shopify-timber/snippets/comment.liquid',
    'shopify-timber/snippets/oldIE-js.liquid',
    'shopify-timber/snippets/onboarding-empty-collection.liquid',
    'shopify-timber/snippets/onboarding-featured-collections.liquid',
    'shopify-timber/snippets/onboarding-featured-products.liquid',
    'shopify-timber/snippets/product-grid-item.liquid',
    'shopify-timber/snippets/respond.liquid',
    'shopify-timber/snippets/search-bar.liquid',
    'shopify-timber/snippets/social-meta-tags.liquid',
    'shopify-timber/snippets/tags-article.liquid',
    'shopify-timber/templates/404.liquid',
    'shopify-timber/templates/article.liquid',
    'shopify-timber/templates/blog.liquid',
    'shopify-timber/templates/cart.liquid',
    'shopify-timber/templates/collection.liquid',
    'shopify-timber/templates/collection.list.liquid',
    'shopify-timber/templates/customers/account.liquid',
    'shopify-timber/templates/customers/activate_account.liquid',
    'shopify-timber/templates/customers/addresses.liquid',
    'shopify-timber/templates/customers/login.liquid',
    'shopify-timber/templates/customers/order.liquid',
    'shopify-timber/templates/customers/register.liquid',
    'shopify-timber/templates/customers/reset_password.liquid',
    'shopify-timber/templates/gift_card.liquid',
    'shopify-timber/templates/index.liquid',
    'shopify-timber/templates/list-collections.liquid',
    'shopify-timber/templates/page.contact.liquid',
    'shopify-timber/templates/page.liquid',
    'shopify-timber/templates/product.liquid',
    'shopify-timber/templates/search.liquid'
  ];

  fixtures.forEach(name => {
    it('should convert ' + name, function() {
      let exp = name.replace(/\.liquid$/, '.hbs');
      assert.equal(converter.convert(fixture(name)), expected(exp));
    });
  });
});
